### ISSUE TITLE
Error: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by Priti101** [joe-antognini/kozai#1] opened 2020-05-08 07:59 UTC
![kozai_q](https://user-images.githubusercontent.com/40427349/81384791-22c3fb80-914d-11ea-8327-d7b1382f2fb7.png)

**Comment by joe-antognini** [comment] 2020-05-10 07:21
Thanks for bringing this to my attention @Priti101!  I think that the cause of this is that numpy doesn't coerce floats into ints when setting the shape of an array of zeros.  (Perhaps it did in an earlier version.)

This was just one of a number of issues that have grown as this package aged.  I have been doing some work to modernize it so that now it uses Python 3, pins dependencies, and conforms better to PEP guidelines.  If you try installing the latest version on master now hopefully you will find that the tutorial runs without issue.  I am hoping to get a release out to pip tomorrow as well.

Let me know if these changes fix your issue and I will be able to close this once the new version is out on pip.

**Comment by joe-antognini** [comment] 2020-05-11 00:24
The new version 0.3.0 is now out on pip, so you should be able to upgrade with `pip install --upgrade kozai`.  Note that the new version requires Python 3.

Let me know if this fixes the issue you observed or run into any others.

**Comment by Priti101** [comment] 2020-05-11 03:27
Thank you @joe-antognini! The new version is running smoothly with Python 3.

**Closed as completed** 2020-05-11 05:03 UTC
